// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.jetbrainsKotlinAndroid) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.navigation.safeargs) apply false
    alias(libs.plugins.hilt.dagger) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.dependencyAnalysis)
    alias(libs.plugins.compose.compiler) apply false
}

dependencyAnalysis {
    issues {
        all {
            onUnusedDependencies {
                severity('fail')
            }
            onUsedTransitiveDependencies {
                severity('warn')
            }
            onIncorrectConfiguration {
                severity('fail')
            }
            onUnusedAnnotationProcessors {
                severity('fail')
            }
            onRedundantPlugins {
                severity('fail')
            }
        }
    }
}



