[versions]
## Dependencies version
appcompat = "1.6.1"
material = "1.12.0"
androidxNavigation = "2.7.7"
joda = "2.12.7"
core = "1.5.0"
junitVersion = "4.13.2"
extTest = "1.1.5"
room = "2.6.1"
coroutine = "1.8.1"
composeConstraintLayout = "1.0.1"
composeCompiler = "1.5.14"

## Plugins versions
agp = "8.4.1"
kotlin = "1.9.24"
navigation = "2.7.7"
hilt = "2.51.1"
ksp = "1.9.24-1.0.20"
composeBom = "2024.05.00"
dagp = "1.32.0"


[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
joda-time = { group = "net.danlew", name = "android.joda", version.ref = "joda" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-ext = { group = "androidx.test.ext", name = "junit", version.ref = "extTest" }
androidx-junit = { group = "junit", name = "junit", version.ref = "junitVersion" }


## Room
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

## Dagger
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-hilt-compiler-ksp = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

## Coroutine
coroutine-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }


##Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3"}
androidx-compose-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout-compose" , version.ref = "composeConstraintLayout"}
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler" , version.ref="composeCompiler"}
##Android Studio Preview support
androidx-compose-ui-tooling-debug = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview  = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
##LiveData,ViewModel,Activity
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose"}
androidx-compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose"}
androidx-compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata"}
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose"}
##Icons
androidx-compose-icons-core = { group = "androidx.compose.material", name = "material-icons-core"}
androidx-compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended"}
androidx-compose-window-size = { group = "androidx.compose.material3", name = "material3-window-size-class"}
##Navigation
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose" ,version.ref="androidxNavigation"}
##UI Tests
androidx-ui-compose-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }



[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
hilt-dagger = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dagp" }


