plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.jetbrainsKotlinAndroid)
    alias(libs.plugins.navigation.safeargs)
    alias(libs.plugins.hilt.dagger)
    alias(libs.plugins.ksp)
}

android {
    namespace 'com.note.mynote'
    compileSdk 34

    defaultConfig {
        applicationId "com.note.mynote"
        minSdk 25
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlin{
        jvmToolchain(21)
    }

    buildFeatures {
        compose = true
    }
    composeOptions{
        kotlinCompilerExtensionVersion = "1.5.14"
    }
}


dependencies {
    implementation libs.androidx.appcompat
    implementation libs.android.material
    implementation libs.joda.time
    implementation libs.androidx.test.core
    testImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.ext
    androidTestRuntimeOnly libs.androidx.test.core

    //room
    implementation(libs.room)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler.ksp)

    //dagger hilt
    implementation libs.dagger.hilt
    ksp(libs.dagger.hilt.compiler.ksp)

    //coroutine
    runtimeOnly libs.coroutine.android
    implementation libs.coroutine.core

    //Compose
    androidTestImplementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.constraint.layout
    runtimeOnly libs.androidx.compose.compiler
    implementation libs.androidx.compose.activity
    implementation libs.androidx.compose.viewmodel
    implementation libs.androidx.compose.livedata
    implementation libs.androidx.compose.icons.core
    implementation libs.androidx.compose.icons.extended
    implementation libs.androidx.compose.window.size
    implementation libs.androidx.compose.navigation
    implementation libs.androidx.lifecycle.runtime.compose
    implementation libs.androidx.compose.ui.tooling.preview
    debugImplementation libs.androidx.compose.ui.tooling.debug
    implementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.ui.compose.test.junit4
    debugRuntimeOnly libs.androidx.ui.compose.test.manifest
}