plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.jetbrainsKotlinAndroid)
    alias(libs.plugins.navigation.safeargs)
    alias(libs.plugins.hilt.dagger)
    alias(libs.plugins.ksp)
    alias(libs.plugins.compose.compiler)
}

android {
    namespace 'com.note.mynote'
    compileSdk 34

    defaultConfig {
        applicationId "com.note.mynote"
        minSdk 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_22
        targetCompatibility JavaVersion.VERSION_22
    }
    kotlin{
        jvmToolchain(22)
    }

    buildFeatures {
        compose = true
    }
}


dependencies {
    implementation(libs.androidx.core.ktx)
    implementation libs.androidx.appcompat
    implementation libs.android.material
    implementation libs.joda.time
    implementation libs.androidx.test.core
    implementation project(':network')
    testImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.ext
    androidTestRuntimeOnly libs.androidx.test.core
    testImplementation(libs.mockito.core)
    androidTestImplementation(libs.mockito.android)


    //room
    implementation(libs.room)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler.ksp)

    //dagger hilt
    implementation libs.dagger.hilt
    ksp(libs.dagger.hilt.compiler.ksp)

    //coroutine
    runtimeOnly libs.coroutine.android
    implementation libs.coroutine.core

    //Retrofit
    implementation libs.retrofit2
    implementation libs.retrofit2.converter.gson

    //Compose
    androidTestImplementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.constraint.layout
    implementation libs.androidx.compose.activity
    implementation libs.androidx.compose.viewmodel
    implementation libs.androidx.compose.livedata
    implementation libs.androidx.compose.icons.core
    implementation libs.androidx.compose.icons.extended
    implementation libs.androidx.compose.window.size
    implementation libs.androidx.compose.navigation
    implementation libs.androidx.compose.lifecycle.runtime
    implementation libs.androidx.ui.compose.tooling.preview
    debugImplementation libs.androidx.ui.compose.tooling.debug
    implementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.ui.compose.test.junit4
    debugRuntimeOnly libs.androidx.ui.compose.test.manifest

}